# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a922d2b9458b39b27864224a33cac945c580f6d66b5b3fbf0aa5a7819302dd1caa15b59d14623e63b7902ae3f2c62c54cd412c7a070c2eb4f9129eb6f4867de

test:
  secret_key_base: 0fcb07026b07587d28a03270ceafa2de36eb4b0bc3056c8a5274b5ec01f6cebd4c4fd6ab58a963ccfa34315671121afdf37d464e1163f54ae87a0441b7fb4ad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
